require 'rake/clean'

EXT_CONF = 'ext/gofuncs/extconf.rb'
MAKEFILE = 'ext/gofuncs/Makefile'
MODULE = 'ext/gofuncs/main.so'
SRC = Dir.glob('ext/gofuncs/*.c')
SRC << MAKEFILE

CLEAN.include [ 'ext/gofuncs/*.o', MODULE ]
CLOBBER.include [ 'config.save', 'ext/gofuncs/mkmf.log', 'ext/gofuncs/extconf.h', MAKEFILE ]

file MAKEFILE => EXT_CONF do |t|
    Dir::chdir(File::dirname(EXT_CONF)) do
        unless sh "ruby #{File::basename(EXT_CONF)}"
            $stderr.puts "Failed to run extconf"
            break
        end
    end
end
file MODULE => SRC do |t|
    Dir::chdir(File::dirname(EXT_CONF)) do
        unless sh "make"
            $stderr.puts "make failed"
            break
        end
    end
end
desc "Build the native library"
task :build => MODULE
